# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "ea-rz"
BBFILE_PATTERN_ea-rz = "^${LAYERDIR}/"
BBFILE_PRIORITY_ea-rz = "17"
LAYERSERIES_COMPAT_ea-rz = "scarthgap"
